---
title: "TXSScan results analysis focusing on other SS"
output: html_notebook
---

```{r}
library(tidyverse)
theme_set(theme_classic(base_size = 16))
```

```{r message=FALSE}
data_dir <- "/Users/gabriema/PostdocUMIK/Activities/Legionome/Data/"

LegioInfo <- read_tsv(paste0(data_dir,"LegioID_legionomePangenome_genus.tsv")) %>% 
  mutate(tax_short = word(gtdbtk.classification, start = 6, end = 7, sep = ";"),
                                      species_cluster = word(strain_cluster, start = 1, end = 2, sep = "_"))

txsscan_files <- list.files(paste0(data_dir, "/TXSScan_results/Summary_output"), full.names = TRUE)

txsscan_results <- read_tsv(txsscan_files[1], skip = 3, id = "filename")
for (i in 2:length(txsscan_files)){
  txsscan_results_tmp <- read_tsv(txsscan_files[i], skip = 3, id = "filename")
  txsscan_results <- bind_rows(txsscan_results, txsscan_results_tmp)
}
colnames(txsscan_results) <- paste0("TXSScan_",gsub("TXSScan-1.1.0/bacteria/diderm/","",colnames(txsscan_results)))
txsscan_results <- txsscan_results %>% mutate(legio_id = word(word(TXSScan_filename, 11, sep = stringr::fixed("/")), 1, sep = "_")) %>% select(-TXSScan_filename, -TXSScan_replicon)
txsscan_results <- txsscan_results %>% relocate(legio_id, 1)
#write_tsv(txsscan_results, paste0(data_dir, "/TXSScan_results/TXSScan_summary_output_tot.tsv"))
```

```{r}
LegioInfo_txss <- LegioInfo %>% left_join(txsscan_results)

LegioInfo_txss_isolation <- LegioInfo_txss %>% pivot_longer(starts_with("TXSS")) %>% 
  group_by(legio_id, isolated, genus_cluster) %>% 
  summarise(TXSS_sum = sum(value)) 
LegioInfo_txss_isolation %>%  filter(genus_cluster %in% c(1,6,13)) %>%
  ggplot(aes(isolated, TXSS_sum)) + 
  geom_boxplot() + 
  facet_wrap(~genus_cluster)

LegioInfo_txss_isolation %>% group_by(genus_cluster) %>% 
  filter(genus_cluster %in% c(1,6,13)) %>% rstatix::t_test(TXSS_sum ~ isolated)
# Out of 3 genera which present isolated and non-isolated genomes, only one presents a significantly lower number of TXSS in non-isolated genomes
# This suggest that yes MAGs can possible reduce the TXSS detected, but this effect is not too dramatic

#write_tsv(LegioInfo_txss, paste0(data_dir, "/TXSScan_results/LegioInfo_TXSS.tsv"))
```

```{r}
LegioInfo_txss %>% mutate(TXSS_profile = paste(TXSScan_T1SS > 0, TXSScan_T2SS > 0, TXSScan_T3SS > 0, TXSScan_T5aSS > 0, TXSScan_T5bSS > 0, TXSScan_T5cSS > 0, TXSScan_T6SSi > 0, sep = "_")) %>% 
  group_by(species_cluster) %>% 
  summarise(n_genomes = n(), different_TXSS_profiles = length(unique(TXSS_profile))) %>% 
  filter(n_genomes > 1) %>% 
  group_by(different_TXSS_profiles > 1) %>% 
  summarise(n = n())
# Intra-species variability is not that high as only 5/21 

varying_species <- LegioInfo_txss %>% mutate(TXSS_profile = paste(TXSScan_T1SS > 0, TXSScan_T2SS > 0, TXSScan_T3SS > 0, TXSScan_T5aSS > 0, TXSScan_T5bSS > 0, TXSScan_T5cSS > 0, TXSScan_T6SSi > 0, sep = "_")) %>% 
  group_by(species_cluster) %>% 
  summarise(n_genomes = n(), different_TXSS_profiles = length(unique(TXSS_profile))) %>% 
  filter(different_TXSS_profiles > 1) %>% pull(species_cluster)

LegioInfo_txss %>% filter(species_cluster %in% varying_species) %>% 
  select(legio_id, species_cluster, tax_short, genus_cluster, starts_with("TXSScan_T")) %>% view()
```


```{r}

LegioInfo_txss_summary <- LegioInfo_txss %>% pivot_longer(starts_with("TXSScan_")) %>% 
  mutate(presence = as.numeric(value > 0)) %>% 
  group_by(genus_cluster, name) %>% 
  summarise(n_genomes = n(), presences = sum(presence), percentage_presence = presences/n_genomes)

LegioInfo_txss_summary %>% 
  ggplot(aes(genus_cluster, name, fill = percentage_presence)) +
  geom_tile()

```

##### Flagella and pili
```{r}
LegioInfo_txss_summary %>% 
  group_by(name) %>% filter(sum(presences) > 0) %>% # Remove TXSS without any presences
  filter(str_detect(name, "Flag|T4a")) %>% 
  ggplot() +
  geom_col(aes(genus_cluster, n_genomes, fill = "n genomes")) +
  geom_col(aes(genus_cluster, presences, fill = "present")) +
  facet_wrap(~name)

# To check if the presence of non-flagellated genomes in genus cluster 1 is linked to AAI threshold used -> no
LegioInfo_txss %>% pivot_longer(starts_with("TXSScan_")) %>% 
  mutate(presence = as.numeric(value > 0)) %>% filter(str_detect(name, "Flag")) %>% 
  filter(genus_cluster == 1) %>% 
  group_by(genus_cluster_literature) %>% 
  summarise(n_genomes = n(), presences = sum(presence), percentage_presence = presences/n_genomes) %>% 
  ggplot() +
  geom_col(aes(genus_cluster_literature, n_genomes, fill = "n genomes")) +
  geom_col(aes(genus_cluster_literature, presences, fill = "present"))

```
####### Other secretion systems
```{r}
LegioInfo_txss_summary_SS <- LegioInfo_txss_summary %>% 
  group_by(name) %>% filter(sum(presences) > 0) %>% # Remove TXSS without any presences
  filter(!str_detect(name, "Flag|T4a"))  # To remove flagella and pili
LegioInfo_txss_summary_SS

LegioInfo_txss_summary %>% 
  ggplot() +
  geom_col(aes(genus_cluster, n_genomes, fill = "n genomes")) +
  geom_col(aes(genus_cluster, presences, fill = "present")) +
  facet_wrap(~name)

```

```{r}
LegioInfo_txss %>% 
  mutate(pT4SSt_present = TXSScan_pT4SSt > 0) %>% 
  group_by(genus_cluster, isolated, pT4SSt_present) %>% 
  summarise( n = n())


```

```{r}
LegioInfo_txss_T1SS <- LegioInfo_txss %>% 
  #filter(genus_cluster_bestConcordance %in% c(6,13)) %>% 
  mutate(species_cluster = word(strain_cluster, start = 1, end = 2, sep = "_")) %>% 
  group_by(species_cluster, genus_cluster) %>% 
  summarise(n_genomes = n(),
            presences_T1SS = sum(TXSScan_T1SS > 0))

LegioInfo_txss_T1SS %>% group_by(genus_cluster) %>% 
  summarise(species_positives_perc = sum(presences_T1SS > 0)/n())

LegioInfo_txss %>% 
  ggplot(aes(as.factor(genus_cluster), TXSScan_T1SS)) +
  geom_boxplot()


```
```{r}
LegioInfo_txss_T4SS <- LegioInfo_txss %>% 
  #filter(genus_cluster_bestConcordance %in% c(6,13)) %>% 
  mutate(species_cluster = word(strain_cluster, start = 1, end = 2, sep = "_")) %>% 
  group_by(species_cluster, genus_cluster) %>% 
  summarise(n_genomes = n(),
            presences_T4SS = sum(TXSScan_pT4SSt > 0))

LegioInfo_txss %>% 
  #filter(genus_cluster_bestConcordance %in% c(6,13)) %>% 
  mutate(species_cluster = word(strain_cluster, start = 1, end = 2, sep = "_")) %>% 
  filter(TXSScan_pT4SSt > 0) %>% 
  pull(species_cluster) %>% unique() %>% length()

LegioInfo_txss_T4SS %>% group_by(genus_cluster) %>% 
  summarise(species_positives_perc = sum(presences_T4SS > 0)/n())

LegioInfo_txss %>% 
  ggplot(aes(as.factor(genus_cluster), TXSScan_pT4SSt)) +
  geom_boxplot()


```

```{r}
LegioInfo_txss_T5SS <- LegioInfo_txss %>% 
  #filter(genus_cluster_bestConcordance %in% c(6,13)) %>% 
  mutate(species_cluster = word(strain_cluster, start = 1, end = 2, sep = "_")) %>% 
  group_by(species_cluster, genus_cluster) %>% 
  summarise(n_genomes = n(),
            presences_T5aSS = sum(TXSScan_T5aSS > 0),
            presences_T5cSS = sum(TXSScan_T5cSS > 0),
            presences_T5SS = sum((TXSScan_T5aSS > 0) + (TXSScan_T5cSS > 0)))

LegioInfo_txss_T5SS %>% group_by(genus_cluster) %>% 
  summarise(species_positives_perc = sum(presences_T5SS > 0)/n())

LegioInfo_txss %>% 
  ggplot(aes(as.factor(genus_cluster), TXSScan_T5aSS)) +
  geom_boxplot()


```

```{r}
LegioInfo_txss_T6SS <- LegioInfo_txss %>% 
  #filter(genus_cluster_bestConcordance %in% c(6,13)) %>% 
  mutate(species_cluster = word(strain_cluster, start = 1, end = 2, sep = "_")) %>% 
  group_by(species_cluster, genus_cluster) %>% 
  summarise(n_genomes = n(),
            presences_T6SS = sum(TXSScan_T6SSi > 0))

LegioInfo_txss_T6SS %>% group_by(genus_cluster) %>% 
  summarise(species_positives_perc = sum(presences_T6SS > 0)/n())


```

```{r}
# Check whether within species presence is conserved

txss_withinSpecies_heterogeneity <- LegioInfo_txss %>% pivot_longer(starts_with("TXSScan_")) %>% 
  mutate(presence = as.numeric(value > 0), species_cluster = word(strain_cluster, start = 1, end = 2, sep = "_")) %>%
  filter(!str_detect(name, "Flag|T4a") & str_detect(name, "_T")) %>% 
  group_by(species_cluster, name, isolated) %>% 
  summarise(tax = paste(unique(gtdbtk.classification), collapse = ","),
            n_genomes = n(), presences = sum(presence), fract_presence = presences/n_genomes) %>% 
  filter(fract_presence > 0 & fract_presence < 1)
  
txss_withinSpecies_heterogeneity


```

```{r}
LegioInfo_txss %>% pivot_longer(starts_with("TXSScan_")) %>% 
  group_by(species_info, name) %>% 
  mutate(presence = as.numeric(value > 0)) %>% 
  summarise(n_genomes = n(), presences = sum(presence), fract_presence = presences/n_genomes) %>% 
  filter(presences > 0) %>% 
  ggplot() +
  geom_col(aes(species_info, n_genomes, fill = "n genomes")) +
  geom_col(aes(species_info, presences, fill = "present")) +
  facet_wrap(~name) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

```